import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Header from '../Header';
import Footer from '../Footer';
import { DarkModeProvider } from '@/providers';
import { getDictionary } from './dictionaries.js';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'CD Fullstack | Carine Dupuis',
  description: 'Carine Dupuis Portfolio, generated by create next app',
  authors: [{ name: 'carine Dupuis', url: 'https://github.com/chewbacca234/' }],
  applicationName: 'Portfolio Carine Dupuis',
  creator: 'Carine Dupuis | CD Fullstack',
  generator: 'Next.js',
  keywords: [
    'react',
    'nextjs',
    'threejs',
    'portfolio',
    'fullsatck',
    'web application',
    'mobile application',
    'responsive',
    'freelance',
  ],
  icons: '/images/favicon-CDFullstack.ico',
};

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { [lang: string]: string };
}>) {
  // console.log('lang:', lang);
  const dict = await getDictionary(lang);

  return (
    <html lang={lang}>
      <body className={inter.className}>
        <DarkModeProvider>
          <Header dict={dict} lang={lang} />
          {children}
          <Footer dict={dict} />
        </DarkModeProvider>
      </body>
    </html>
  );
}
