import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer, Header } from '@/components';
import { DarkModeProvider } from '@/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'CD Fullstack | Carine Dupuis',
  description: 'Carine Dupuis Portfolio, generated by create next app',
  authors: [{ name: 'carine Dupuis', url: 'https://github.com/chewbacca234/' }],
  applicationName: 'Portfolio Carine Dupuis',
  creator: 'Carine Dupuis | CD Fullstack',
  generator: 'Next.js',
  keywords: [
    'react',
    'nextjs',
    'threejs',
    'portfolio',
    'fullsatck',
    'web application',
    'mobile application',
    'responsive',
    'freelance',
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkModeProvider>
          <Header />
          {children}
          <Footer />
        </DarkModeProvider>
      </body>
    </html>
  );
}
